version: "3.8"
services:
  db:
    container_name: bookmark-me-db
    image: postgres
    environment:
      POSTGRES_USER: yellowhatpro
      POSTGRES_DB: bookmark-me-db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - bookmark-me-db-data:/data/db
volumes:
  bookmark-me-db-data: {}
